version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:1.0
    container_name: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    command: npm run dev -- --host